import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { createSessionToken, isValidSession, SESSION_COOKIE, SESSION_MAX_AGE } from "../session";

// ─── createSessionToken ───────────────────────────────────────────────────────

describe("createSessionToken", () => {
  beforeEach(() => {
    // 각 테스트 전 환경변수 초기화
    vi.unstubAllEnvs();
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("should throw when SESSION_SECRET is not set", () => {
    // Arrange — 환경변수 제거
    vi.stubEnv("SESSION_SECRET", "");

    // Act & Assert
    expect(() => createSessionToken()).toThrow("SESSION_SECRET 환경변수가 설정되지 않았음");
  });

  it("should return a base64-encoded token when SESSION_SECRET is set", () => {
    // Arrange
    vi.stubEnv("SESSION_SECRET", "test-secret");

    // Act
    const token = createSessionToken();

    // Assert — base64 형식 검증 (문자셋: A-Z, a-z, 0-9, +, /, =)
    expect(token).toMatch(/^[A-Za-z0-9+/=]+$/);
  });

  it("should encode 'authenticated:{secret}' in base64", () => {
    // Arrange
    vi.stubEnv("SESSION_SECRET", "my-secret");

    // Act
    const token = createSessionToken();
    const decoded = Buffer.from(token, "base64").toString("utf-8");

    // Assert
    expect(decoded).toBe("authenticated:my-secret");
  });

  it("should return different tokens for different secrets", () => {
    // Arrange & Act
    vi.stubEnv("SESSION_SECRET", "secret-A");
    const tokenA = createSessionToken();

    vi.stubEnv("SESSION_SECRET", "secret-B");
    const tokenB = createSessionToken();

    // Assert
    expect(tokenA).not.toBe(tokenB);
  });

  it("should return the same token for the same secret (deterministic)", () => {
    // Arrange
    vi.stubEnv("SESSION_SECRET", "fixed-secret");

    // Act
    const token1 = createSessionToken();
    const token2 = createSessionToken();

    // Assert — 같은 시크릿이면 항상 동일한 토큰
    expect(token1).toBe(token2);
  });
});

// ─── isValidSession ───────────────────────────────────────────────────────────

describe("isValidSession", () => {
  beforeEach(() => {
    vi.stubEnv("SESSION_SECRET", "test-secret");
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("should return false when token is undefined", () => {
    // Act & Assert
    expect(isValidSession(undefined)).toBe(false);
  });

  it("should return false when token is empty string", () => {
    // Act & Assert
    expect(isValidSession("")).toBe(false);
  });

  it("should return false for an arbitrary invalid token", () => {
    // Act & Assert
    expect(isValidSession("invalid-token")).toBe(false);
    expect(isValidSession("abc123")).toBe(false);
  });

  it("should return true for a valid token generated by createSessionToken", () => {
    // Arrange
    const validToken = createSessionToken();

    // Act & Assert
    expect(isValidSession(validToken)).toBe(true);
  });

  it("should return false when token was generated with a different secret", () => {
    // Arrange — 다른 시크릿으로 토큰 생성
    vi.stubEnv("SESSION_SECRET", "other-secret");
    const tokenFromOtherSecret = createSessionToken();

    // 시크릿을 원래대로 복원
    vi.stubEnv("SESSION_SECRET", "test-secret");

    // Act & Assert — 다른 시크릿으로 만든 토큰은 무효
    expect(isValidSession(tokenFromOtherSecret)).toBe(false);
  });

  it("should return false when SESSION_SECRET is missing (graceful failure)", () => {
    // Arrange — 환경변수 제거 (SESSION_SECRET 없는 환경)
    vi.stubEnv("SESSION_SECRET", "");
    const token = "YXV0aGVudGljYXRlZDp0ZXN0LXNlY3JldA=="; // 임의 토큰

    // Act & Assert — 예외를 던지지 않고 false 반환
    expect(() => isValidSession(token)).not.toThrow();
    expect(isValidSession(token)).toBe(false);
  });
});

// ─── 상수 ─────────────────────────────────────────────────────────────────────

describe("session constants", () => {
  it("SESSION_COOKIE should be a non-empty string", () => {
    expect(typeof SESSION_COOKIE).toBe("string");
    expect(SESSION_COOKIE.length).toBeGreaterThan(0);
  });

  it("SESSION_MAX_AGE should be 30 days in seconds", () => {
    const thirtyDaysInSeconds = 60 * 60 * 24 * 30;
    expect(SESSION_MAX_AGE).toBe(thirtyDaysInSeconds);
  });
});
